//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessProcess
    {
        public int Row_Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string Object { get; set; }
        public string SPName { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> ActiveRecord { get; set; }
        public Nullable<bool> ActiveRecordSet { get; set; }
        public string RecordSet { get; set; }
    }
}
