//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CampaignCollateral
{
    public int Row_Id { get; set; }
    public Nullable<int> CampaignId { get; set; }
    public string Type { get; set; }
    public string Content { get; set; }
    public Nullable<int> CampaignTimeLineId { get; set; }
    public Nullable<decimal> DwellTimeMin { get; set; }
    public Nullable<decimal> DwellTimeMax { get; set; }
    public Nullable<int> VisitMin { get; set; }
    public Nullable<int> VisitMax { get; set; }
    public Nullable<int> MaxMessages { get; set; }
}
