//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    
    public partial class GetAllUsersJobStatus
    {
        public Nullable<int> UserType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Row_Id { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Job_Id { get; set; }
    }
}
