//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    
    public partial class GetCalenderUsers
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UserType { get; set; }
        public int UserId { get; set; }
        public string Color { get; set; }
        public Nullable<int> CalendarId { get; set; }
    }
}
