//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GetEventEmailORPrintData
{
    public int ROW_ID { get; set; }
    public string TO_EMAIL { get; set; }
    public string FROM_EMAIL { get; set; }
    public string SUBJECT { get; set; }
    public string MESSAGE_BODY { get; set; }
    public Nullable<bool> IS_ACTIVE { get; set; }
}
