//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GetGroupCalendarUsers
{
    public int Row_Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public Nullable<int> UserType { get; set; }
    public Nullable<int> UserId { get; set; }
    public string Color { get; set; }
    public Nullable<int> CalendarId { get; set; }
}
