//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Row_Id { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Property_Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Primary_Contact_Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Required_By_Date { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
    }
}
