//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class JobCopyType
{
    public int Row_Id { get; set; }
    public Nullable<int> Org_Id { get; set; }
    public string Type { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
    public Nullable<System.DateTime> Created { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<System.DateTime> Updated { get; set; }
    public Nullable<int> UpdatedBy { get; set; }
}
