//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int Row_ID { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string FileName { get; set; }
        public string SentDate { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
