//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class OrderSubItem
{
    public int Row_Id { get; set; }
    public Nullable<int> OrderItemId { get; set; }
    public Nullable<int> ProductSubGroupId { get; set; }
    public string OptionSelected { get; set; }
    public Nullable<System.DateTime> Created { get; set; }
}
