//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ProductCompany
{
    public int Row_Id { get; set; }
    public Nullable<int> ProductId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<bool> Enable { get; set; }
}
