//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Product
{
    public int Row_Id { get; set; }
    public string XeroCode { get; set; }
    public string ProductDescription { get; set; }
    public string XeroItemDescription { get; set; }
    public Nullable<decimal> SalesUnitPrice { get; set; }
    public string SalesAccountCode { get; set; }
    public string SalesTaxType { get; set; }
    public Nullable<int> ProductGroupId { get; set; }
    public Nullable<bool> WebOrderable { get; set; }
    public string WebName { get; set; }
    public string WebDescription { get; set; }
    public string WebType { get; set; }
    public string WebOptions { get; set; }
    public Nullable<int> WebOptionMin { get; set; }
    public Nullable<int> WebOptionMax { get; set; }
    public Nullable<int> ProductSubGroupId { get; set; }
    public Nullable<int> OrgId { get; set; }
}
