//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SelectOrg
{
    public int OrgId { get; set; }
    public string OrgName { get; set; }
    public string Logolocation { get; set; }
    public string subdomain { get; set; }
    public Nullable<System.TimeSpan> BH_StartTime { get; set; }
    public Nullable<System.TimeSpan> BH_EndTime { get; set; }
    public string ThemeName { get; set; }
}
