//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    
    public partial class SelectOrderableProducts
    {
        public int Row_Id { get; set; }
        public string PrimaryProductGroup { get; set; }
        public string CompanyName { get; set; }
        public string WebName { get; set; }
        public string WebDescription { get; set; }
        public string WebType { get; set; }
        public string WebOptions { get; set; }
        public Nullable<int> WebOptionMin { get; set; }
        public Nullable<int> WebOptionMax { get; set; }
        public Nullable<decimal> SalesUnitPrice { get; set; }
        public string SecondaryProductGroup { get; set; }
    }
}
