//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    
    public partial class SelectEventsBySearchValue
    {
        public int Row_Id { get; set; }
        public Nullable<int> CalendarId { get; set; }
        public string EventId { get; set; }
        public string RecurringEventId { get; set; }
        public string ColorId { get; set; }
        public string Attendees { get; set; }
        public Nullable<bool> AttendeesOmitted { get; set; }
        public Nullable<bool> AnyoneCanAddSelf { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Kind { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> MovedOn { get; set; }
        public string Status { get; set; }
        public string Recurrence { get; set; }
        public string Organizer { get; set; }
        public string Creator { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Transperancy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Visibility { get; set; }
        public Nullable<bool> IsAllDay { get; set; }
        public string RecurrenceID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
