//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SelectJobAttachmentFolders
{
    public int ROW_ID { get; set; }
    public Nullable<int> PARENT_FOLDER_ID { get; set; }
    public string PARENT_FOLDER_NAME { get; set; }
    public string TAGS { get; set; }
    public string Folder { get; set; }
    public Nullable<int> CountFolder { get; set; }
}
