//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SelectJobAttachmentTemplate
{
    public int Row_Id { get; set; }
    public int OrgId { get; set; }
    public int Job_Id { get; set; }
    public string FileName { get; set; }
    public string FileExtension { get; set; }
    public Nullable<int> FileSize { get; set; }
    public byte[] File { get; set; }
    public string GroupType { get; set; }
    public string Tags { get; set; }
    public string Folder { get; set; }
    public Nullable<bool> Selected { get; set; }
    public Nullable<int> SelectedBy { get; set; }
    public string FilePath { get; set; }
    public string Comments { get; set; }
    public string Thumbnail { get; set; }
    public Nullable<System.DateTime> UPLOAD_DATETIME { get; set; }
    public Nullable<int> UPLOAD_BY { get; set; }
    public string UPLOAD_STATUS { get; set; }
    public string FirstName { get; set; }
    public string Fname2 { get; set; }
    public string MobileNumber { get; set; }
    public string PackageNumber { get; set; }
    public Nullable<int> CommentCount { get; set; }
    public string Company_Name { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
}
