//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    
    public partial class SpGetAllUsers
    {
        public int Row_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string XeroName { get; set; }
        public string UserRoll { get; set; }
        public Nullable<int> ProductGroupId { get; set; }
        public string GroupsName { get; set; }
    }
}
