//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor_Fact
    {
        public int Row_Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> ReceiverUDID { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public Nullable<int> MessageCount { get; set; }
        public Nullable<int> CampaignId { get; set; }
    }
}
