//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetConfig
    {
        public int Row_Id { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<decimal> AdvInterval { get; set; }
        public string AdvChannel { get; set; }
        public string ProxUDID { get; set; }
        public string Major { get; set; }
        public string Minor { get; set; }
        public string Power { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Range { get; set; }
        public string Firmware { get; set; }
        public string Location { get; set; }
        public string PassCode { get; set; }
        public Nullable<int> CampaignId { get; set; }
    }
}
