//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Row_Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<System.Guid> AssetGUID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ManufactureId { get; set; }
        public string ManufactureModel { get; set; }
        public string Battery { get; set; }
        public string FactorySerialNo { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> PurchasePriceExGST { get; set; }
        public string PurchaseCurrency { get; set; }
        public Nullable<decimal> PurchaseExchangeRate { get; set; }
        public string MaxRange { get; set; }
        public string Passcode { get; set; }
        public Nullable<int> PurchaseInvoiceId__PurchaseInvoiceId { get; set; }
    }
}
