//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarUser
    {
        public int Row_Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CalendarId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
