//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignNotification
    {
        public int Row_Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> CampaignSittingId { get; set; }
        public string NotificationType { get; set; }
        public string NotificationMsg { get; set; }
        public string ReceiverUDID { get; set; }
        public Nullable<System.DateTime> FireDatetime { get; set; }
        public Nullable<int> Badge { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
