//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignAsset
    {
        public int Row_Id { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> AssetConfigId { get; set; }
        public Nullable<int> ConfiguredBy { get; set; }
    }
}
