//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevEntities : DbContext
    {
        public DevEntities()
            : base("name=DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Applications { get; set; }
        public DbSet<Asset> Assets { get; set; }
        public DbSet<AssetAllocation> AssetAllocations { get; set; }
        public DbSet<AssetConfig> AssetConfigs { get; set; }
        public DbSet<AssetHealthMeasure> AssetHealthMeasures { get; set; }
        public DbSet<AssetService> AssetServices { get; set; }
        public DbSet<AssetStatu> AssetStatus { get; set; }
        public DbSet<BusinessProcess> BusinessProcesses { get; set; }
        public DbSet<Calendar> Calendars { get; set; }
        public DbSet<CalendarUser> CalendarUsers { get; set; }
        public DbSet<Campaign> Campaigns { get; set; }
        public DbSet<CampaignAsset> CampaignAssets { get; set; }
        public DbSet<CampaignCollateral> CampaignCollaterals { get; set; }
        public DbSet<CampaignNotification> CampaignNotifications { get; set; }
        public DbSet<CampaignSitting> CampaignSittings { get; set; }
        public DbSet<CampaignTimeLine> CampaignTimeLines { get; set; }
        public DbSet<CancelledOrder> CancelledOrders { get; set; }
        public DbSet<ColorMaster> ColorMasters { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyMail> CompanyMails { get; set; }
        public DbSet<CompanyOrder> CompanyOrders { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventTracking> EventTrackings { get; set; }
        public DbSet<Mail> Mails { get; set; }
        public DbSet<OrderContact> OrderContacts { get; set; }
        public DbSet<OrderEvent> OrderEvents { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderType> OrderTypes { get; set; }
        public DbSet<Organisation> Organisations { get; set; }
        public DbSet<ProductCompany> ProductCompanies { get; set; }
        public DbSet<ProductGroup> ProductGroups { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductSchedule> ProductSchedules { get; set; }
        public DbSet<ProductUser> ProductUsers { get; set; }
        public DbSet<Property> Properties { get; set; }
        public DbSet<PropertyInvoice> PropertyInvoices { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Street> Streets { get; set; }
        public DbSet<Suburb> Suburbs { get; set; }
        public DbSet<tmp> tmps { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<Visitor_Fact> Visitor_Fact { get; set; }
    }
}
