//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSchedule
    {
        public int Row_Id { get; set; }
        public string XeroCode { get; set; }
        public string Value { get; set; }
        public string Title { get; set; }
        public Nullable<int> ColorId { get; set; }
    }
}
