//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Row_Id { get; set; }
        public string XeroCode { get; set; }
        public string ProductDescription { get; set; }
        public string XeroItemDescription { get; set; }
        public Nullable<decimal> SalesUnitPrice { get; set; }
        public string SalesAccountCode { get; set; }
        public string SalesTaxType { get; set; }
    }
}
