//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp
    {
        public int ID { get; set; }
        public string pmDescription { get; set; }
        public string smDescription { get; set; }
        public string mstr_list_item_desc { get; set; }
        public string delete_ind { get; set; }
        public string address_line_1 { get; set; }
        public string limit_id { get; set; }
        public string licType { get; set; }
    }
}
