//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.CalendarServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalendarServices.ICT_SyncGoogleCalendar")]
    public interface ICT_SyncGoogleCalendar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendars", ReplyAction="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendarsResponse")]
        string SyncGoogleCalendars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendars", ReplyAction="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendarsResponse")]
        System.Threading.Tasks.Task<string> SyncGoogleCalendarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendar", ReplyAction="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendarResponse")]
        void SyncGoogleCalendar(string calendarId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendar", ReplyAction="http://tempuri.org/ICT_SyncGoogleCalendar/SyncGoogleCalendarResponse")]
        System.Threading.Tasks.Task SyncGoogleCalendarAsync(string calendarId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICT_SyncGoogleCalendarChannel : OrderManagement.Web.CalendarServices.ICT_SyncGoogleCalendar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CT_SyncGoogleCalendarClient : System.ServiceModel.ClientBase<OrderManagement.Web.CalendarServices.ICT_SyncGoogleCalendar>, OrderManagement.Web.CalendarServices.ICT_SyncGoogleCalendar {
        
        public CT_SyncGoogleCalendarClient() {
        }
        
        public CT_SyncGoogleCalendarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CT_SyncGoogleCalendarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CT_SyncGoogleCalendarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CT_SyncGoogleCalendarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SyncGoogleCalendars() {
            return base.Channel.SyncGoogleCalendars();
        }
        
        public System.Threading.Tasks.Task<string> SyncGoogleCalendarsAsync() {
            return base.Channel.SyncGoogleCalendarsAsync();
        }
        
        public void SyncGoogleCalendar(string calendarId) {
            base.Channel.SyncGoogleCalendar(calendarId);
        }
        
        public System.Threading.Tasks.Task SyncGoogleCalendarAsync(string calendarId) {
            return base.Channel.SyncGoogleCalendarAsync(calendarId);
        }
    }
}
